# Generated by Django 5.1.1 on 2024-10-16 11:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History_panjang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.FloatField()),
                ('panjang_asal', models.CharField(max_length=255)),
                ('result', models.FloatField()),
                ('panjang_tujuan', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='History_suhu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.FloatField()),
                ('suhu_asal', models.CharField(max_length=255)),
                ('result', models.FloatField()),
                ('suhu_tujuan', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
